name: green_quest_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.1+2

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.3+1
  hive: ^2.2.3
  cupertino_icons: ^1.0.8
  auto_route: ^8.1.3
  flutter_riverpod: ^2.5.1
  permission_handler: ^11.3.1
  flutter_screenutil: ^5.9.1
  fluttertoast: ^8.2.5
  google_fonts: ^6.2.1
  loading_animation_widget: ^1.2.1
  cached_network_image: ^3.3.1
  image_picker: ^1.1.1
  file_picker: ^8.0.3
  json_annotation: ^4.9.0
  firebase_core: ^2.31.1
  firebase_auth: ^4.19.6
  firebase_ui_auth: ^1.14.0
  webview_flutter: ^4.8.0
  pinput: ^4.0.0
  http: ^1.2.1
  animated_notch_bottom_bar: ^1.0.3
  pretty_dio_logger: ^1.3.1
  flutter_svg: ^2.0.10+1
  freezed_annotation: ^2.4.1
  intl: ^0.19.0
  google_mobile_ads: ^5.1.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  flutter_lints: ^4.0.0
  riverpod_lint:

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/launcher_icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/home_screen_images/
    - assets/images/login_screen/
    - assets/images/logo/
    - assets/images/navigating_icons/
    - assets/images/others/
    - assets/images/navigating_icons/
    - assets/images/onboarding_screen_images/
    - assets/images/signup_screen_images/
    - assets/images/splash_screen_images/
    - assets/images/task_screen_images/
    - assets/images/wallet/
    - assets/icon/
    - assets/images/profile/
